# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    defaults:
      run:
        shell: bash
        working-directory: ./example-app    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Cache ubuntu build venv
        if: ${{ runner.os }} == "Ubuntu"
        id: cached-ubuntu-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/work/iac-labs/iac-labs/example-app/.venv
          key: ${{ runner.os }}-venv
      - name: Cache windows build venv
        if: ${{ runner.os }} != "Ubuntu"
        id: cached-windows-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: D:\a\iac-labs\iac-labs\example-app\.venv
          key: ${{ runner.os }}-venv

  lint:    
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./example-app
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Cache ubuntu build venv
      if: ${{ runner.os }} == "Linux"
      id: cached-ubuntu-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/iac-labs/iac-labs/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Cache windows build venv
      if: ${{ runner.os }} != "Linux"
      id: cached-windows-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: D:\a\iac-labs\iac-labs\example-app\.venv
        key: ${{ runner.os }}-venv
    - name: poetry lint
      run: |
        poetry run task lint
