# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
        matrix:
          os: [ "ubuntu-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        working-directory: ./example-app
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
  # You may pin to the exact commit or the version.
  # uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b
      uses: snok/install-poetry@v1.3.4
      with:
    # The Poetry version to install
        virtualenvs-create: true
        virtualenvs-in-project: false
        installer-parallel: true

  lint:    
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]      
    runs-on: ${{ matrix.os }}
      
    defaults:
      run:
        working-directory: ./example-app
      
    needs: build
     
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
      with:
        virtualenvs-create: true
        virtualenvs-in-project: false
        installer-parallel: true 
        
    - name: poetry lint
      run: |
        poetry run task lint

